export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0f] text-white">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-12">Last updated: April 6, 2026</p>

        <div className="space-y-10 text-white/70 leading-relaxed">

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using ContractGuard ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p>ContractGuard provides AI-assisted contract analysis for informational purposes only. The Service uses the Anthropic Claude API to identify potentially risky clauses in contracts uploaded by users.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Not Legal Advice</h2>
            <p>The analysis provided by ContractGuard is generated by artificial intelligence and is for informational purposes only. It does not constitute legal advice and should not be relied upon as such. ContractGuard is not a law firm and does not provide legal services. Always consult a qualified attorney before signing any contract.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Limitation of Liability</h2>
            <p>To the maximum extent permitted by applicable law, ContractGuard shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service, including but not limited to damages resulting from reliance on AI-generated analysis, errors or omissions in the analysis, or any decisions made based on the Service output.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Accuracy Disclaimer</h2>
            <p>AI-generated analysis may be incomplete, inaccurate, or inapplicable to your specific situation. ContractGuard makes no representations or warranties regarding the accuracy, completeness, or reliability of any analysis provided.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. User Responsibilities</h2>
            <p>You are solely responsible for any contracts you upload to the Service. You must not upload contracts containing information that you are not authorized to share. You agree to use the Service only for lawful purposes.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Payment and Refunds</h2>
            <p>Payments are processed securely via Stripe. All purchases are one-time payments for a single analysis report. Due to the nature of digital content, refunds are generally not available once a PDF report has been generated or downloaded. If you experience a technical issue, please contact us at <a href="mailto:aeoseiya@gmail.com" className="text-emerald-400 hover:text-emerald-300">aeoseiya@gmail.com</a>.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Intellectual Property</h2>
            <p>The Service, including its design, code, and branding, is the property of ContractGuard. You retain all rights to the contracts you upload. The AI-generated analysis reports are provided for your personal use only.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Modifications to Terms</h2>
            <p>ContractGuard reserves the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Contact</h2>
            <p>For questions about these Terms, please contact us at <a href="mailto:aeoseiya@gmail.com" className="text-emerald-400 hover:text-emerald-300">aeoseiya@gmail.com</a>.</p>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-white/10">
          <a href="/" className="text-emerald-400 hover:text-emerald-300 text-sm">← Back to ContractGuard</a>
        </div>
      </div>
    </div>
  );
}
